name: Publishing of libs and plugin on release

on:
  release:
    types: [ published ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish api
        env:
          MAVEN_REPOSITORY_LOGIN: ${{ secrets.MAVEN_REPOSITORY_LOGIN }}
          MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
        run:  ./gradlew :kotlinx.fuzz.api:publish

      - name: Publish engine
        env:
          MAVEN_REPOSITORY_LOGIN: ${{ secrets.MAVEN_REPOSITORY_LOGIN }}
          MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
        run:  ./gradlew :kotlinx.fuzz.engine:publish

      - name: Publish jazzer
        env:
          MAVEN_REPOSITORY_LOGIN: ${{ secrets.MAVEN_REPOSITORY_LOGIN }}
          MAVEN_REPOSITORY_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
        run:  ./gradlew :kotlinx.fuzz.jazzer:publish

      - name: Publish gradle plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew :kotlinx.fuzz.gradle:publish
#        run:  ./gradlew :kotlinx.fuzz.gradle:publishPlugins
